// Hashes of prebuilt portable_pty_rs binaries for each platform.
// Used by the build hook to verify downloaded artifacts.
//
// Generated by tool/write_asset_hashes.dart

// dart format off

/// The GitHub release tag from which prebuilt binaries are downloaded.
const String releaseTag = 'portable_pty-v0.0.7-beta.2';

/// Maps platform labels to artifact info and SHA256 hashes.
const Map<String, AssetHash> assetHashes = {
  'linux-x64': AssetHash(
    tarball: 'pty-linux-x64.tar.gz',
    hash: '814a1e2859945c2c667b247873edb14cc16c82a27d042bf4abf60e1ce456fdc2',
  ),
  'linux-arm64': AssetHash(
    tarball: 'pty-linux-arm64.tar.gz',
    hash: '4e32d1f831368a1f3616ad273a15ea386ad584e93147f8dfd3476f7052706e87',
  ),
  'macos-arm64': AssetHash(
    tarball: 'pty-macos-arm64.tar.gz',
    hash: '2b7e2adbbb7a8bf4e5e145c0627d9913f71792b6566e451ff41e67d215127c0c',
  ),
  'macos-x64': AssetHash(
    tarball: 'pty-macos-x64.tar.gz',
    hash: '13bb51fa872d9afac0c4599b888111bb6540b26b6fe22dff619e1c7925597204',
  ),
  'windows-x64': AssetHash(
    tarball: 'pty-windows-x64.tar.gz',
    hash: '45c9128734d422a397938924a3242df48a2a13459a79169c049d3a96d178d066',
  ),
  'windows-arm64': AssetHash(
    tarball: 'pty-windows-arm64.tar.gz',
    hash: 'b09b2d1cfa320471678e5641350924dad4100a3798d6e557b7d279055a9ffe3a',
  ),
  'android-arm64': AssetHash(
    tarball: 'pty-android-arm64.tar.gz',
    hash: '51cc345ce8060223c0bf178611061ff5716d14d9f0a6c0c1ccf7a98021ea8d92',
  ),
  'android-arm': AssetHash(
    tarball: 'pty-android-arm.tar.gz',
    hash: '3aef38b36476a8ce4b5344594ea7de536409fa9337dcc3a4658175b076c44fd7',
  ),
  'android-x64': AssetHash(
    tarball: 'pty-android-x64.tar.gz',
    hash: 'd99feec672718ead325dc6da7fce5ca3df8cacc0c1e3fd608b19b9be925c4a5b',
  ),
  'ios-arm64': AssetHash(
    tarball: 'pty-ios-arm64.tar.gz',
    hash: 'b883e148b6cb30870fa6fc60fa8f59f60f581ccb65bf436f5c68f082498ecb96',
  ),
  'ios-sim-arm64': AssetHash(
    tarball: 'pty-ios-sim-arm64.tar.gz',
    hash: '445f5f61ec6b3319437b9ce995c93bb04b56f75c5d2f7373f374f8fffc03f59f',
  ),
  'ios-sim-x64': AssetHash(
    tarball: 'pty-ios-sim-x64.tar.gz',
    hash: '45cf8c3cdf340cc2d1560c8ba76a434d29333e5aa42920294573afb12802f4cc',
  ),
};

/// Describes a prebuilt artifact with its download filename and integrity hash.
class AssetHash {
  /// The tarball filename in the GitHub release (e.g. "pty-linux-x64.tar.gz").
  final String tarball;

  /// SHA256 hash of the extracted library file.
  final String hash;

  const AssetHash({required this.tarball, required this.hash});
}
