// Hashes of prebuilt portable_pty_rs binaries for each platform.
// Used by the build hook to verify downloaded artifacts.
//
// Generated by tool/write_asset_hashes.dart

// dart format off

/// The GitHub release tag from which prebuilt binaries are downloaded.
const String releaseTag = 'portable_pty-v0.0.7-beta.1';

/// Maps platform labels to artifact info and SHA256 hashes.
const Map<String, AssetHash> assetHashes = {
  'linux-x64': AssetHash(
    tarball: 'pty-linux-x64.tar.gz',
    hash: '814a1e2859945c2c667b247873edb14cc16c82a27d042bf4abf60e1ce456fdc2',
  ),
  'linux-arm64': AssetHash(
    tarball: 'pty-linux-arm64.tar.gz',
    hash: '4e32d1f831368a1f3616ad273a15ea386ad584e93147f8dfd3476f7052706e87',
  ),
  'macos-arm64': AssetHash(
    tarball: 'pty-macos-arm64.tar.gz',
    hash: '2b7e2adbbb7a8bf4e5e145c0627d9913f71792b6566e451ff41e67d215127c0c',
  ),
  'macos-x64': AssetHash(
    tarball: 'pty-macos-x64.tar.gz',
    hash: '13bb51fa872d9afac0c4599b888111bb6540b26b6fe22dff619e1c7925597204',
  ),
  'windows-x64': AssetHash(
    tarball: 'pty-windows-x64.tar.gz',
    hash: '55459d86efee5202dfe243addf6ebfb2048f790e71ced7dd15a89cb2975693e5',
  ),
  'windows-arm64': AssetHash(
    tarball: 'pty-windows-arm64.tar.gz',
    hash: '717ad2c70753bc90ddc8711e4f04558314d2c06cb3c46ce1b82469265e8267d1',
  ),
  'android-arm64': AssetHash(
    tarball: 'pty-android-arm64.tar.gz',
    hash: 'be4d2e82542974ed2f7c2fca69838af355a714e464d15cb47dba5d506c1b36ce',
  ),
  'android-arm': AssetHash(
    tarball: 'pty-android-arm.tar.gz',
    hash: '36725416503158ecbf5851f180334068e50016097620a0408c426d61a37590ee',
  ),
  'android-x64': AssetHash(
    tarball: 'pty-android-x64.tar.gz',
    hash: '83255613e2ce22f2df2f2127ae2b9c5bcace2d4199bf37c333e633de1c9fb7fa',
  ),
  'ios-arm64': AssetHash(
    tarball: 'pty-ios-arm64.tar.gz',
    hash: 'b883e148b6cb30870fa6fc60fa8f59f60f581ccb65bf436f5c68f082498ecb96',
  ),
  'ios-sim-arm64': AssetHash(
    tarball: 'pty-ios-sim-arm64.tar.gz',
    hash: '445f5f61ec6b3319437b9ce995c93bb04b56f75c5d2f7373f374f8fffc03f59f',
  ),
  'ios-sim-x64': AssetHash(
    tarball: 'pty-ios-sim-x64.tar.gz',
    hash: '45cf8c3cdf340cc2d1560c8ba76a434d29333e5aa42920294573afb12802f4cc',
  ),
};

/// Describes a prebuilt artifact with its download filename and integrity hash.
class AssetHash {
  /// The tarball filename in the GitHub release (e.g. "pty-linux-x64.tar.gz").
  final String tarball;

  /// SHA256 hash of the extracted library file.
  final String hash;

  const AssetHash({required this.tarball, required this.hash});
}
