// Hashes of prebuilt portable_pty_rs binaries for each platform.
// Used by the build hook to verify downloaded artifacts.
//
// Generated by tool/write_asset_hashes.dart

// dart format off

/// The GitHub release tag from which prebuilt binaries are downloaded.
const String releaseTag = 'v0.0.3';

/// Maps platform labels to artifact info and SHA256 hashes.
///
/// The key is the platform label (e.g. "linux-x64"), the value contains the
/// tarball filename and the SHA256 hash of the library inside.
const Map<String, AssetHash> assetHashes = {
  'linux-x64': AssetHash(
    tarball: 'pty-linux-x64.tar.gz',
    hash: '1f50dd808de16316ff1a9e0714da57d9b495a2b989735d1725799229e3680e57',
  ),
  'linux-arm64': AssetHash(
    tarball: 'pty-linux-arm64.tar.gz',
    hash: 'a17f5c81d342b8602a6e612dbf48358aee434fe8ddb035324fe0da8c46c5a3b1',
  ),
  'macos-arm64': AssetHash(
    tarball: 'pty-macos-arm64.tar.gz',
    hash: '43bf99c83016e97ba22154f41563dbb8b34eb030f2549bca45121b0387c1c8fb',
  ),
  'macos-x64': AssetHash(
    tarball: 'pty-macos-x64.tar.gz',
    hash: 'ed4c503ff2c90165f0217d420b0312829e281040552fadd002592331a0e79326',
  ),
  'windows-x64': AssetHash(
    tarball: 'pty-windows-x64.tar.gz',
    hash: '675153f1ae4a9e5e900dd3de34009befffe693c9c9016072b30c2773df458a2b',
  ),
  'android-arm64': AssetHash(
    tarball: 'pty-android-arm64.tar.gz',
    hash: '286d260c59863fdb6559fef6dd64e97297c76f59a6efc3a7aa624b489574f9be',
  ),
  'android-arm': AssetHash(
    tarball: 'pty-android-arm.tar.gz',
    hash: '636cb13794b11b2730f5046134cf5a57f2167fde242245ac189b10e592db25ad',
  ),
  'android-x64': AssetHash(
    tarball: 'pty-android-x64.tar.gz',
    hash: 'beb67af48ecd73b77b0993969af62325b5aa8b7d6705f594d62aea711ac744aa',
  ),
  'ios-arm64': AssetHash(
    tarball: 'pty-ios-arm64.tar.gz',
    hash: '58ae6321b47055a25861f00750edfad39f70eb37b1b56dba543ed6809b594eff',
  ),
  'ios-sim-arm64': AssetHash(
    tarball: 'pty-ios-sim-arm64.tar.gz',
    hash: '5162e4fc39bec987fb422b5acb59b2f4006b6e6c1255d5e1aa229387fdd4f0b3',
  ),
};

/// Describes a prebuilt artifact with its download filename and integrity hash.
class AssetHash {
  /// The tarball filename in the GitHub release (e.g. "pty-linux-x64.tar.gz").
  final String tarball;

  /// SHA256 hash of the extracted library file.
  final String hash;

  const AssetHash({required this.tarball, required this.hash});
}
