// Hashes of prebuilt ghostty-vt binaries for each platform.
// Used by the build hook to verify downloaded artifacts.
//
// Generated by tool/write_asset_hashes.dart

// dart format off

/// The GitHub release tag from which prebuilt binaries are downloaded.
const String releaseTag = 'v0.0.3';

/// Maps artifact tarball names to SHA256 hashes of the extracted library file.
///
/// The key is the platform label (e.g. "linux-x64"), the value contains the
/// tarball filename and the SHA256 hash of the library inside.
const Map<String, AssetHash> assetHashes = {
  'linux-x64': AssetHash(
    tarball: 'vte-linux-x64.tar.gz',
    hash: 'c7a6a9f126306cc2956d2f62e693ac189d86f99fc44ab5a5f9736daca0ab8369',
  ),
  'linux-arm64': AssetHash(
    tarball: 'vte-linux-arm64.tar.gz',
    hash: '76fba680591b8dbd3da91eec20f6a2beb3967c349bb2015ef48999748fc27d06',
  ),
  'macos-arm64': AssetHash(
    tarball: 'vte-macos-arm64.tar.gz',
    hash: 'c43fc3b20b24ff34bc38cdec84c17b1d819db388d358e63cba52cf03de2a5d5d',
  ),
  'macos-x64': AssetHash(
    tarball: 'vte-macos-x64.tar.gz',
    hash: '5a0162bb11c37acf8a9d4d0ff7d538349020db5e09173dc369aa831048261718',
  ),
  'windows-x64': AssetHash(
    tarball: 'vte-windows-x64.tar.gz',
    hash: '05121b91b3e701ee64c1ccde3c7d3c34c8ce3ce705ba6f9fb4d6e24a59570c2e',
  ),
  'windows-arm64': AssetHash(
    tarball: 'vte-windows-arm64.tar.gz',
    hash: '0fb8020d4e03c3e65cb80a14f01ee6fb0d0f1dbaf43d5df5d6413cf64063746f',
  ),
  'android-arm64': AssetHash(
    tarball: 'vte-android-arm64.tar.gz',
    hash: '03940115e19066a0c0bf7f936162db5be1f5fdde32e5bd1ed2ee98f61bfefb6d',
  ),
  'android-arm': AssetHash(
    tarball: 'vte-android-arm.tar.gz',
    hash: '62bafb746346233d7b6803be715520e44d0d6cba57bf1b501ca6ea1e1a6d1ffa',
  ),
  'android-x64': AssetHash(
    tarball: 'vte-android-x64.tar.gz',
    hash: '40ee8d3fe6bd325ba681c755b59806d6ff282106974bfc95c020851397a25b26',
  ),
};

/// Describes a prebuilt artifact with its download filename and integrity hash.
class AssetHash {
  /// The tarball filename in the GitHub release (e.g. "vte-linux-x64.tar.gz").
  final String tarball;

  /// SHA256 hash of the extracted library file.
  final String hash;

  const AssetHash({required this.tarball, required this.hash});
}
