// Hashes of prebuilt ghostty-vt binaries for each platform.
// Used by the build hook to verify downloaded artifacts.
//
// Generated by tool/write_asset_hashes.dart

// dart format off

/// The GitHub release tag from which prebuilt binaries are downloaded.
const String releaseTag = 'v0.0.3';

/// Maps platform labels to artifact info and SHA256 hashes.
const Map<String, AssetHash> assetHashes = {
  'linux-x64': AssetHash(
    tarball: 'vte-linux-x64.tar.gz',
    hash: '11f3246188192668d469efb6014fdcb175da5d79448d70167c3b855928efefb6',
  ),
  'linux-arm64': AssetHash(
    tarball: 'vte-linux-arm64.tar.gz',
    hash: '362a71a7fdf7462d00d56c20f08334e8e33e3b3b0761c92971990bfd24fe29f0',
  ),
  'macos-arm64': AssetHash(
    tarball: 'vte-macos-arm64.tar.gz',
    hash: '4b1a41bf837abc0fb833709d27f1413f2ccb3e02f7a73a661234bb7e219f6e7c',
  ),
  'macos-x64': AssetHash(
    tarball: 'vte-macos-x64.tar.gz',
    hash: '5a0162bb11c37acf8a9d4d0ff7d538349020db5e09173dc369aa831048261718',
  ),
  'windows-x64': AssetHash(
    tarball: 'vte-windows-x64.tar.gz',
    hash: '05121b91b3e701ee64c1ccde3c7d3c34c8ce3ce705ba6f9fb4d6e24a59570c2e',
  ),
  'windows-arm64': AssetHash(
    tarball: 'vte-windows-arm64.tar.gz',
    hash: '0fb8020d4e03c3e65cb80a14f01ee6fb0d0f1dbaf43d5df5d6413cf64063746f',
  ),
  'android-arm64': AssetHash(
    tarball: 'vte-android-arm64.tar.gz',
    hash: '98d0fa5c19edcf8a57a817da8a4999d3cf0af350511b77b2211475fa10c82a1c',
  ),
  'android-arm': AssetHash(
    tarball: 'vte-android-arm.tar.gz',
    hash: '1d8449da046a120ab1f1404db5af14b1e46227d6c5f30bfe3fe8f12edf47df65',
  ),
  'android-x64': AssetHash(
    tarball: 'vte-android-x64.tar.gz',
    hash: 'd6e1793356ece4d509e34c8867ad933c183fc145261bdb1ebfaff2616b74efa9',
  ),
};

/// Describes a prebuilt artifact with its download filename and integrity hash.
class AssetHash {
  /// The tarball filename in the GitHub release (e.g. "vte-linux-x64.tar.gz").
  final String tarball;

  /// SHA256 hash of the extracted library file.
  final String hash;

  const AssetHash({required this.tarball, required this.hash});
}
