// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Open a new PTY with the given dimensions.
///
/// @param rows    Number of rows.
/// @param cols    Number of columns.
/// @param out     Receives the opaque PTY handle on success.
/// @return PORTABLE_PTY_OK on success.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Uint16,
    ffi.Uint16,
    ffi.Pointer<ffi.Pointer<portable_pty_t>>,
  )
>(symbol: 'portable_pty_open')
external int _portable_pty_open(
  int rows,
  int cols,
  ffi.Pointer<ffi.Pointer<portable_pty_t>> out,
);

portable_pty_result_t portable_pty_open(
  int rows,
  int cols,
  ffi.Pointer<ffi.Pointer<portable_pty_t>> out,
) => portable_pty_result_t.fromValue(_portable_pty_open(rows, cols, out));

/// Spawn a child process attached to the PTY.
///
/// @param handle  PTY handle from portable_pty_open().
/// @param cmd     Null-terminated executable path.
/// @param argv    Null-terminated array of null-terminated argument strings,
/// or NULL to use cmd as the sole argument.
/// @param envp    Null-terminated array of "KEY=VALUE" strings, or NULL to
/// inherit the current environment.
/// @return PORTABLE_PTY_OK on success.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<portable_pty_t>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>(symbol: 'portable_pty_spawn')
external int _portable_pty_spawn(
  ffi.Pointer<portable_pty_t> handle,
  ffi.Pointer<ffi.Char> cmd,
  ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
  ffi.Pointer<ffi.Pointer<ffi.Char>> envp,
);

portable_pty_result_t portable_pty_spawn(
  ffi.Pointer<portable_pty_t> handle,
  ffi.Pointer<ffi.Char> cmd,
  ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
  ffi.Pointer<ffi.Pointer<ffi.Char>> envp,
) => portable_pty_result_t.fromValue(
  _portable_pty_spawn(handle, cmd, argv, envp),
);

/// Read bytes from the PTY master side (child's stdout).
///
/// @return Number of bytes read, or -1 on error/EOF.
@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<portable_pty_t>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int portable_pty_read(
  ffi.Pointer<portable_pty_t> handle,
  ffi.Pointer<ffi.Uint8> buf,
  int len,
);

/// Write bytes to the PTY master side (child's stdin).
///
/// @return Number of bytes written, or -1 on error.
@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<portable_pty_t>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int portable_pty_write(
  ffi.Pointer<portable_pty_t> handle,
  ffi.Pointer<ffi.Uint8> buf,
  int len,
);

/// Resize the PTY.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<portable_pty_t>, ffi.Uint16, ffi.Uint16)
>(symbol: 'portable_pty_resize')
external int _portable_pty_resize(
  ffi.Pointer<portable_pty_t> handle,
  int rows,
  int cols,
);

portable_pty_result_t portable_pty_resize(
  ffi.Pointer<portable_pty_t> handle,
  int rows,
  int cols,
) => portable_pty_result_t.fromValue(_portable_pty_resize(handle, rows, cols));

/// Get the current PTY size.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<portable_pty_t>,
    ffi.Pointer<ffi.Uint16>,
    ffi.Pointer<ffi.Uint16>,
    ffi.Pointer<ffi.Uint16>,
    ffi.Pointer<ffi.Uint16>,
  )
>(symbol: 'portable_pty_get_size')
external int _portable_pty_get_size(
  ffi.Pointer<portable_pty_t> handle,
  ffi.Pointer<ffi.Uint16> out_rows,
  ffi.Pointer<ffi.Uint16> out_cols,
  ffi.Pointer<ffi.Uint16> out_pixel_width,
  ffi.Pointer<ffi.Uint16> out_pixel_height,
);

portable_pty_result_t portable_pty_get_size(
  ffi.Pointer<portable_pty_t> handle,
  ffi.Pointer<ffi.Uint16> out_rows,
  ffi.Pointer<ffi.Uint16> out_cols,
  ffi.Pointer<ffi.Uint16> out_pixel_width,
  ffi.Pointer<ffi.Uint16> out_pixel_height,
) => portable_pty_result_t.fromValue(
  _portable_pty_get_size(
    handle,
    out_rows,
    out_cols,
    out_pixel_width,
    out_pixel_height,
  ),
);

/// Get the master file descriptor (POSIX) or -1 (Windows).
@ffi.Native<ffi.Int32 Function(ffi.Pointer<portable_pty_t>)>()
external int portable_pty_master_fd(ffi.Pointer<portable_pty_t> handle);

/// Get the child PID, or -1 if no child has been spawned.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<portable_pty_t>)>()
external int portable_pty_child_pid(ffi.Pointer<portable_pty_t> handle);

/// Non-blocking wait for child exit.
///
/// @param out_status  Receives the exit code on success.
/// @return PORTABLE_PTY_OK if child exited, PORTABLE_PTY_ERR_WAIT if still
/// running.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<portable_pty_t>, ffi.Pointer<ffi.Int>)
>(symbol: 'portable_pty_wait')
external int _portable_pty_wait(
  ffi.Pointer<portable_pty_t> handle,
  ffi.Pointer<ffi.Int> out_status,
);

portable_pty_result_t portable_pty_wait(
  ffi.Pointer<portable_pty_t> handle,
  ffi.Pointer<ffi.Int> out_status,
) => portable_pty_result_t.fromValue(_portable_pty_wait(handle, out_status));

/// Blocking wait for child exit.
@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<portable_pty_t>, ffi.Pointer<ffi.Int>)
>(symbol: 'portable_pty_wait_blocking')
external int _portable_pty_wait_blocking(
  ffi.Pointer<portable_pty_t> handle,
  ffi.Pointer<ffi.Int> out_status,
);

portable_pty_result_t portable_pty_wait_blocking(
  ffi.Pointer<portable_pty_t> handle,
  ffi.Pointer<ffi.Int> out_status,
) => portable_pty_result_t.fromValue(
  _portable_pty_wait_blocking(handle, out_status),
);

/// Get the PTY process group leader id.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<portable_pty_t>)>()
external int portable_pty_process_group_leader(
  ffi.Pointer<portable_pty_t> handle,
);

/// Send a signal to the child process (POSIX signal number).
@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<portable_pty_t>, ffi.Int)>(
  symbol: 'portable_pty_kill',
)
external int _portable_pty_kill(ffi.Pointer<portable_pty_t> handle, int signal);

portable_pty_result_t portable_pty_kill(
  ffi.Pointer<portable_pty_t> handle,
  int signal,
) => portable_pty_result_t.fromValue(_portable_pty_kill(handle, signal));

/// Get current terminal mode flags.
@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<portable_pty_t>,
    ffi.Pointer<ffi.Bool>,
    ffi.Pointer<ffi.Bool>,
  )
>(symbol: 'portable_pty_get_mode')
external int _portable_pty_get_mode(
  ffi.Pointer<portable_pty_t> handle,
  ffi.Pointer<ffi.Bool> out_canonical,
  ffi.Pointer<ffi.Bool> out_echo,
);

portable_pty_result_t portable_pty_get_mode(
  ffi.Pointer<portable_pty_t> handle,
  ffi.Pointer<ffi.Bool> out_canonical,
  ffi.Pointer<ffi.Bool> out_echo,
) => portable_pty_result_t.fromValue(
  _portable_pty_get_mode(handle, out_canonical, out_echo),
);

/// Close the PTY and free all resources.
/// Kills the child process if still running. Safe to call with NULL.
@ffi.Native<ffi.Void Function(ffi.Pointer<portable_pty_t>)>()
external void portable_pty_close(ffi.Pointer<portable_pty_t> handle);

final class portable_pty extends ffi.Opaque {}

/// Opaque handle
typedef portable_pty_t = portable_pty;

/// Result codes
enum portable_pty_result_t {
  PORTABLE_PTY_OK(0),
  PORTABLE_PTY_ERR_OPEN(1),
  PORTABLE_PTY_ERR_SPAWN(2),
  PORTABLE_PTY_ERR_RESIZE(3),
  PORTABLE_PTY_ERR_READ(4),
  PORTABLE_PTY_ERR_WRITE(5),
  PORTABLE_PTY_ERR_NULL(6),
  PORTABLE_PTY_ERR_WAIT(7),
  PORTABLE_PTY_ERR_KILL(8),
  PORTABLE_PTY_ERR_MODE(9),
  PORTABLE_PTY_ERR_SIZE(10),
  PORTABLE_PTY_ERR_WAIT_BLOCKING(11),
  PORTABLE_PTY_ERR_PROCESS_GROUP(12);

  final int value;
  const portable_pty_result_t(this.value);

  static portable_pty_result_t fromValue(int value) => switch (value) {
    0 => PORTABLE_PTY_OK,
    1 => PORTABLE_PTY_ERR_OPEN,
    2 => PORTABLE_PTY_ERR_SPAWN,
    3 => PORTABLE_PTY_ERR_RESIZE,
    4 => PORTABLE_PTY_ERR_READ,
    5 => PORTABLE_PTY_ERR_WRITE,
    6 => PORTABLE_PTY_ERR_NULL,
    7 => PORTABLE_PTY_ERR_WAIT,
    8 => PORTABLE_PTY_ERR_KILL,
    9 => PORTABLE_PTY_ERR_MODE,
    10 => PORTABLE_PTY_ERR_SIZE,
    11 => PORTABLE_PTY_ERR_WAIT_BLOCKING,
    12 => PORTABLE_PTY_ERR_PROCESS_GROUP,
    _ => throw ArgumentError('Unknown value for portable_pty_result_t: $value'),
  };
}
